#line 1 "parser.lex.cc"

#line 3 "parser.lex.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

#define YY_FLEX_LEX_COMPAT
extern int yylineno;
int yylineno = 1;

extern char yytext[];

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( yytext, (yytext_ptr), yyleng + 1 ); \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 39
#define YY_END_OF_BUFFER 40
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[193] =
    {   0,
       36,   36,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   40,   38,
       36,   37,   38,   35,    6,   35,    6,    6,   38,    5,
        4,    5,   39,   39,   19,   19,   19,   22,   21,   22,
       25,   24,   25,   28,   27,   28,   31,   30,   31,   34,
       33,   34,   36,   37,    0,    6,    2,    1,    0,    0,
        0,    3,    0,   12,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    9,    0,    0,    1,
        1,    7,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   11,    0,    0,

        0,   18,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   13,    0,    0,
       14,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       17,   15,    0,    0,    0,    0,    0,    8,   10,    0,
        0,    0,    0,    0,    0,   16,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   20,   23,   26,   29,
       32,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    6,    1,    1,    1,    1,
        1,    7,    8,    8,    8,    9,   10,   11,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   13,    1,   14,
        8,   15,    1,   16,   17,   18,   19,   20,   21,   18,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       25,   32,   33,   34,   35,   36,   25,   37,   38,   25,
        1,   39,    1,    1,   40,    1,   41,   18,   42,   43,

       44,   18,   45,   46,   47,   25,   48,   49,   50,   51,
       52,   53,   25,   54,   55,   56,   57,   58,   25,   37,
       59,   25,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[60] =
    {   0,
        1,    1,    1,    2,    2,    1,    1,    1,    3,    1,
        3,    3,    1,    1,    1,    1,    3,    3,    3,    3,
        3,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        3,    3,    3,    3,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2
    } ;

static const flex_int16_t yy_base[208] =
    {   0,
        0,   15,   25,   26,  372,  371,   27,   31,   32,   34,
       35,   36,   37,   38,   39,   41,   42,   51,  375,  378,
       11,  332,   12,  378,   49,   57,   60,   64,   56,  378,
      378,  319,  378,   74,  378,   36,   98,  378,  378,   34,
      378,  378,   40,  378,  378,   47,  378,  378,   48,  378,
      378,   53,   87,  325,   97,   83,  378,  323,    0,   59,
       81,  378,  319,  378,  103,   73,   70,   77,   76,   88,
       97,   90,   93,   95,   98,  100,  134,  147,  118,  316,
      378,    0,  123,  122,  150,  137,  125,  130,  134,  129,
      132,  139,  142,  144,  147,  148,  148,  378,  147,  313,

      311,  378,  147,  120,  150,  155,  155,  274,  258,  223,
      167,  132,  156,  162,  162,  169,  170,  186,  184,  182,
      180,  181,  183,  184,  186,  196,  200,  378,  195,  186,
      378,  191,  203,  205,  208,  209,  215,  214,  215,  216,
      207,  218,  224,  227,  228,  229,  230,  253,  238,  239,
      378,  378,  235,  236,  238,  239,  241,  276,  378,  238,
      242,  248,  250,  252,  253,  378,  271,  274,  276,  279,
      280,  277,  278,  280,  282,  285,  287,  288,  289,  290,
      292,  104,   78,   48,   47,    5,  378,  378,  378,  378,
      378,  378,  336,  339,  342,  345,  348,  351,  354,  357,

      360,  362,  365,    2,  367,  369,  371
    } ;

static const flex_int16_t yy_def[208] =
    {   0,
      193,  193,  194,  194,  195,  195,  196,  196,  197,  197,
      198,  198,  199,  199,  200,  200,  201,  201,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  202,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  203,  204,  192,
      192,  192,  205,  192,  205,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  203,
      192,  204,  192,  192,  206,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  206,

      207,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  207,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,    0,  192,  192,  192,  192,  192,  192,  192,  192,

      192,  192,  192,  192,  192,  192,  192
    } ;

static const flex_int16_t yy_nxt[438] =
    {   0,
      192,   21,   22,   21,   82,   23,   24,   24,   25,   26,
       27,   28,   53,  192,   53,   29,   21,   22,   21,  191,
       23,   24,   24,   25,   26,   27,   28,   31,   31,   33,
       29,   32,   32,   33,   39,   55,   39,   42,   42,   45,
       45,   48,   36,   48,   51,   40,   36,   40,   43,   43,
       46,   46,   49,   51,   49,   52,   66,   56,   55,   56,
       56,  190,  189,   57,   52,   37,   58,   72,   56,   37,
       56,   56,   56,   73,   56,   56,   60,   63,   64,   66,
       74,   75,   63,   61,   63,   63,   76,   83,   53,   72,
       53,   56,  188,   56,   56,   73,   59,   84,   77,   60,

       77,   86,   74,   75,   87,   61,   88,   64,   76,   83,
       89,   90,   63,   63,   67,   85,   68,   91,  187,   92,
       78,   84,   93,   86,   94,   79,   87,   95,   88,   96,
       69,   70,   89,   71,   90,   77,   97,   77,   67,   68,
       91,   92,   98,   78,   93,   99,   94,   79,   77,   95,
       77,   96,   69,   70,   64,   71,  102,  117,  103,   97,
      104,  105,  106,  107,  108,   98,   64,  109,   99,  110,
       78,  125,  111,  112,  113,  114,  116,  118,  117,  102,
      103,  119,  104,  105,  106,  107,  108,  120,  101,  109,
      126,  110,  127,   78,  111,  112,  113,  114,  116,  118,

      128,  129,  130,  119,  131,  132,  124,  133,  134,  120,
      135,  136,  126,  137,  127,  138,  139,  141,  140,  143,
      142,  144,  128,  129,  145,  146,  130,  131,  132,  133,
      134,  147,  135,  136,  148,  137,  149,  150,  138,  141,
      139,  140,  142,  143,  151,  144,  152,  153,  145,  146,
      154,  155,  156,  157,  158,  147,  158,  148,  159,  149,
      150,  160,  123,  161,  162,  151,  163,  164,  152,  165,
      153,  166,  167,  154,  155,  156,  157,  158,  168,  158,
      169,  159,  170,  171,  160,  161,  162,  172,  163,  164,
      173,  165,  174,  166,  167,  175,  176,  122,  177,  178,

      168,  179,  169,  180,  170,  171,  181,  182,  183,  184,
      185,  172,  186,  121,  173,   64,  174,   64,   81,  175,
      176,  177,  178,   64,  179,   81,  180,   54,   62,  181,
      182,  183,  184,  185,   54,  186,   20,   20,   20,   30,
       30,   30,   33,   33,   33,   35,   35,   35,   38,   38,
       38,   41,   41,   41,   44,   44,   44,   47,   47,   47,
       50,   50,   50,   65,   65,   80,   80,   80,   63,   63,
      100,  100,  115,  115,  192,   34,   34,   19,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,

      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192
    } ;

static const flex_int16_t yy_chk[438] =
    {   0,
        0,    1,    1,    1,  204,    1,    1,    1,    1,    1,
        1,    1,   21,    0,   21,    1,    2,    2,    2,  186,
        2,    2,    2,    2,    2,    2,    2,    3,    4,    7,
        2,    3,    4,    8,    9,   23,   10,   11,   12,   13,
       14,   15,    7,   16,   17,    9,    8,   10,   11,   12,
       13,   14,   15,   18,   16,   17,   36,   25,   23,   25,
       25,  185,  184,   26,   18,    7,   26,   40,   27,    8,
       27,   27,   28,   43,   28,   28,   29,   34,   34,   36,
       46,   49,   34,   29,   34,   34,   52,   60,   53,   40,
       53,   56,  183,   56,   56,   43,   27,   61,   55,   29,

       55,   66,   46,   49,   67,   29,   68,   65,   52,   60,
       69,   70,   34,   34,   37,   65,   37,   71,  182,   72,
       55,   61,   73,   66,   74,   55,   67,   75,   68,   76,
       37,   37,   69,   37,   70,   77,   79,   77,   37,   37,
       71,   72,   83,   55,   73,   84,   74,   55,   78,   75,
       78,   76,   37,   37,   85,   37,   86,  104,   87,   79,
       88,   89,   90,   91,   92,   83,  115,   93,   84,   94,
       78,  112,   95,   96,   97,   99,  103,  105,  104,   86,
       87,  106,   88,   89,   90,   91,   92,  107,   85,   93,
      113,   94,  114,   78,   95,   96,   97,   99,  103,  105,

      116,  117,  118,  106,  119,  120,  111,  121,  122,  107,
      123,  124,  113,  125,  114,  126,  127,  130,  129,  133,
      132,  134,  116,  117,  135,  136,  118,  119,  120,  121,
      122,  137,  123,  124,  138,  125,  139,  140,  126,  130,
      127,  129,  132,  133,  141,  134,  142,  143,  135,  136,
      144,  145,  146,  147,  148,  137,  148,  138,  149,  139,
      140,  150,  110,  153,  154,  141,  155,  156,  142,  157,
      143,  160,  161,  144,  145,  146,  147,  158,  162,  158,
      163,  149,  164,  165,  150,  153,  154,  167,  155,  156,
      168,  157,  169,  160,  161,  170,  171,  109,  172,  173,

      162,  174,  163,  175,  164,  165,  176,  177,  178,  179,
      180,  167,  181,  108,  168,  101,  169,  100,   80,  170,
      171,  172,  173,   63,  174,   58,  175,   54,   32,  176,
      177,  178,  179,  180,   22,  181,  193,  193,  193,  194,
      194,  194,  195,  195,  195,  196,  196,  196,  197,  197,
      197,  198,  198,  198,  199,  199,  199,  200,  200,  200,
      201,  201,  201,  202,  202,  203,  203,  203,  205,  205,
      206,  206,  207,  207,   19,    6,    5,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,

      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[40] =
    {   0,
1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 
        };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "parser.l"
#line 2 "parser.l"
// -------------------------------------------------------
// File: parser.l
// Desc: parser for HelpNdoc.exe stream Tool 1.0
//       With this tool, You can create HTML Help file on
//       the command line console.
//
// Autor: Jens Kallup <kallup.jens@web.de>
// Copy : (c) 2022 by Jens Kallup
//
// only for private use !
// -------------------------------------------------------
#include "misc.hh"

#define YYDEBUG 0

#include "parser.tab.hh"

// Forward declerations ----------------------------------
void Number();
void HexaNumber();
void count(void);

int yyerror(const char*);

int line_row = 1;
int line_col = 1;

std::vector<char> tmpvec;

void handle_str();

// HelpNdoc API related ----------------------------------
namespace HelpNDoc_Version7_9_1 {
// --------------------------------------------------------------
// type's for an argument of a single function ...
// --------------------------------------------------------------
using HelpNDocAPI_ArgumentType = std::variant<
    int,                // is integer
    double,             // is double
    std::string         // is std::string
>;
using HelpNDocAPI_ArgumentMap = std::map<
    int,                // argument no.
    HelpNDocAPI_ArgumentType
>;
// --------------------------------------------------------------
// this class stands for a single object :
// --------------------------------------------------------------
class HelpNDocAPI_Object {
private:
    std::map<
        std::string,              // function name
        HelpNDocAPI_ArgumentMap   // arguments
    > Functions;
public:
    // constructor's:
    //HelpNDocAPI_Object(                           // ctor
    //    const char* func,                         // function name
    //    HelpNDocAPI_ArgumentMap args) {           // arguments
    //    Functions [ std::string(func) ] = args;
    //}
    HelpNDocAPI_Object(std::string func) { }
    
    // destructor:
    ~HelpNDocAPI_Object() { }
};

// --------------------------------------------------------------
// this is the main class of all objects that are available
// in the current version of HelpNDoc 7.9.1 ...
// --------------------------------------------------------------
class HelpNDocAPI {
private:
    // List of objects:
    std::vector< HelpNDocAPI_Object > HndUtils;                // Various utility methods.
    std::vector< HelpNDocAPI_Object > HndBuilds;               // Properties and methods for Builds.
    std::vector< HelpNDocAPI_Object > HndBuildsEx;             // Additional properties and methods for Builds.
    std::vector< HelpNDocAPI_Object > HndBuildsMeta;           // Access to builds meta data.
    std::vector< HelpNDocAPI_Object > HndBuildsMetaEx;         // Additional methods related to builds meta data.
    std::vector< HelpNDocAPI_Object > HndBuildsStatus;         // Handle relationship between builds and statuses.
    std::vector< HelpNDocAPI_Object > HndBuildsStatusEx;       // Additional methods to handle relationship between builds and statuses.
    std::vector< HelpNDocAPI_Object > HndBuildsTags;           // Handle relationship between builds and tags.
    std::vector< HelpNDocAPI_Object > HndBuildsTagsEx;         // Additional methods to handle relationship between builds and tags.
    std::vector< HelpNDocAPI_Object > HndDictionaries;         // Manage dictionaries and live spell check.
    std::vector< HelpNDocAPI_Object > HndEditor;               // Create and manage a topic editor.
    std::vector< HelpNDocAPI_Object > HndEditorHelper;         // Additional methods to manage a topic editor.
    std::vector< HelpNDocAPI_Object > HndJsSearchEngine;       // Methods to manage the JavaScript search engine.
    std::vector< HelpNDocAPI_Object > HndKeywords;             // Properties and methods for keywords.
    std::vector< HelpNDocAPI_Object > HndKeywordsMeta;         // Access to topics meta data.
    std::vector< HelpNDocAPI_Object > HndLibraryItems;         // Properties and methods for library items.
    std::vector< HelpNDocAPI_Object > HndLibraryItemsEx;       // Additional properties and methods for library items.
    std::vector< HelpNDocAPI_Object > HndLibraryItemsCache;    // Library items cache.
    std::vector< HelpNDocAPI_Object > HndLibraryItemsMeta;     // Access to library items meta data.
    std::vector< HelpNDocAPI_Object > HndProjects;             // Properties and methods for projects.
    std::vector< HelpNDocAPI_Object > HndProjectsEx;           // Additional properties and methods for projects.
    std::vector< HelpNDocAPI_Object > HndProjectsMeta;         // Access to project meta data.
    std::vector< HelpNDocAPI_Object > HndProjectsMetaEx;       // Additional methods to access project meta data.
    std::vector< HelpNDocAPI_Object > HndStatus;               // Properties and methods for Statuses.
    std::vector< HelpNDocAPI_Object > HndTags;                 // Properties and methods for Tags.
    std::vector< HelpNDocAPI_Object > HndTemplates;            // Properties and methods for Templates.
    std::vector< HelpNDocAPI_Object > HndTemplatesEx;          // Additional properties and methods for Templates.
    std::vector< HelpNDocAPI_Object > HndTopics;               // Create, edit and manage topics within the current project.
    std::vector< HelpNDocAPI_Object > HndTopicsEx;             // Additional properties and methods for Topics.
    std::vector< HelpNDocAPI_Object > HndTopicsKeywords;       // Handle relationship between topics and keywords.
    std::vector< HelpNDocAPI_Object > HndTopicsKeywordsEx;     // Additional properties and methods to handle relationship between topics and keywords.
    std::vector< HelpNDocAPI_Object > HndTopicsMeta;           // Access to topics meta data.
    std::vector< HelpNDocAPI_Object > HndTopicsProperties;     // Handle relationship between topics and properties.
    std::vector< HelpNDocAPI_Object > HndTopicsTags;           // Handle relationship between topics and tags.
    
    // Global types:
    std::vector< HelpNDocAPI_Object > THndBuildInfo;
    std::vector< HelpNDocAPI_Object > THndBuildInfoArray;
    std::vector< HelpNDocAPI_Object > THndDictionaryInfo;

    // placeholder's:
    static std::string _String ;
    static std::string _Bool   ;
    static std::string _Integer;
    static std::string _TColor ;
    
    HelpNDocAPI_ArgumentMap result_map = { {0, _String}, { 1, _String } };
    
    // -----------------------------------------
    // HndUtils:
    // Various utility methods.
    // availabel members ...
    // -----------------------------------------
    std::map< std::string, HelpNDocAPI_ArgumentMap > HndUtils_FunctionNames = {
        // Filter a string to make it alpha-numeric only. Converts accented characters too.
        {std::string("FilterAlphaNumericString"), {
            { 0, _String },   // 0 = the result parameter: String
            { 1, _String },   // 1 = aStr
            { 2, _Bool   },   // 2 = const doKeepSpaces
            { 3, _Bool   },   // 3 = const doKeepUnderscore
            { 4, _Bool   }    // 4 = const doKeepDash
            }
        },
        
        {std::string("HexToTColor"  ), result_map },    // Converts an hexadecimal value to a TColor
        {std::string("HTMLDecode"   ), result_map },    // Converts a string that has been HTML-encoded into a decoded string.
        {std::string("HTMLEncode"   ), result_map },    // Converts a string into an HTML-encoded string.
        {std::string("HTMLEscape"   ), result_map },    // Escape HTML entities so that they can be included in HTML text or attribute,
        {std::string("HTMLToText"   ), result_map },    // Converts a HTML content to simple text without any tags.
        {std::string("IdnEncode"    ), result_map },    // Performs a International Domain Name (IDNA) Punycode encoding.
        {std::string("IdnDecode"    ), result_map },    // Performs a International Domain Name (IDNA) Punycode decoding.
        {std::string("JSEncode"     ), result_map },    // Encodes a string for use in a JavaScript string literal.
        {std::string("JSEscapeQuote"), result_map },    // Escape single and double quotes in a JavaScript string literal.
        {std::string("TColorToHex"  ), result_map },    // Converts a TColor string value to a heaxadecimal string.
        {std::string("TColorToHex"  ), {                // Converts a TColor string value to a heaxadecimal string.
            { 0, _String },   // 0 = the result parameter: String
            { 1, _String }    // 1 = TColor
            }
        },
        {std::string("UrlEncode"    ), result_map },    // Performs a URL percent encoding.
        {std::string("UrlDecode"    ), result_map }     // Performs a URL percent decoding.
    };
    
    // -----------------------------------------
    // HndBuilds:
    // Properties and methods for Builds.
    // availabel members ...
    // -----------------------------------------
    #if 0
    std::map< std::string, HelpNDocAPI_ArgumentMap > HndBuilds_FunctionNames = {
        {std::string("CreateBuild"         ), result_map },
        {std::string("DeleteAllBuilds"     ), result_map },
        {std::string("DeleteBuild"         ), result_map },
        {std::string("GetBuildEnabled"     ), result_map },
        {std::string("GetBuildFirst"       ), result_map },
        {std::string("GetBuildFirstOfKind" ), result_map },
        {std::string("GetBuildKind"        ), result_map },
        {std::string("GetBuildLast"        ), result_map },
        {std::string("GetBuildList"        ), result_map },
        {std::string("GetBuildName"        ), result_map },
        {std::string("GetBuildNext"        ), result_map },
        {std::string("GetBuildOrder"       ), result_map },
        {std::string("GetBuildOutput"      ), result_map },
        {std::string("GetBuildWithName"    ), result_map },
        {std::string("MoveBuildAfter"      ), result_map },
        {std::string("MoveBuildBefore"     ), result_map },
        {std::string("MoveBuildFirst"      ), result_map },
        {std::string("MoveBuildLast"       ), result_map },
        {std::string("SetBuildEnabled"     ), result_map },
        {std::string("SetBuildKind"        ), result_map },
        {std::string("SetBuildName"        ), result_map },
        {std::string("SetBuildOutput"      ), result_map },
        {std::string("SetBuildTemplate"    ), result_map }
    };
    
    // -----------------------------------------
    // HndBuildsEx:
    // Additional properties and methods for Builds.
    // availabel members ...
    // -----------------------------------------
    std::map< std::string, HelpNDocAPI_ArgumentMap > HndBuildsEx_FunctionNames = {
        {std::string("DuplicateBuild"             ), result_map },
        {std::string("GetBuildListFilteredByName" ), result_map },
        {std::string("GetBuildTemplateOrDefault"  ), result_map },
        {std::string("GetValidBuildOutput"        ), result_map }
    };
    
    // -----------------------------------------
    // HndBuildsMetaEx:
    // Additional methods related to builds meta data.
    // availabel members ...
    // -----------------------------------------
    std::map< std::string, HelpNDocAPI_ArgumentMap > HndBuildsMetaEx_FunctionNames = {
        {std::string("GetChmButtonVisibilityHex"           ), result_map },
        {std::string("GetChmNavigationPaneStyleHex"        ), result_map },
        {std::string("GetProjectDateTimeFormatOverrides"   ), result_map },
        {std::string("GetProjectSettingsOverrides"         ), result_map },
        {std::string("ResetProjectDateTimeFormatOverrides" ), result_map },
        {std::string("ResetProjectSettingsOverrides"       ), result_map },
        {std::string("SetProjectDateTimeOverrides"         ), result_map },
        {std::string("SetProjectSettingsOverrides"         ), result_map }
    };
    
    // -----------------------------------------
    // HndBuildsStatus:
    // Handle relationship between builds and statuses.
    // availabel members ...
    // -----------------------------------------
    std::map< std::string, HelpNDocAPI_ArgumentMap > HndBuildsStatus_FunctionNames = {
        {std::string("AreBuildAndStatusAssociated"   ), result_map },
        {std::string("AssociateBuildWithStatus"      ), result_map },
        {std::string("DissociateAllForStatus"        ), result_map },
        {std::string("DissociateAllForBuild"         ), result_map },
        {std::string("DissociateBuildFromStatus"     ), result_map },
        {std::string("GetStatusAssociatedWithBuild"  ), result_map },
        {std::string("GetBuildsAssociatedWithStatus" ), result_map }
    };
    
    // -----------------------------------------
    // HndBuildsStatusEx:
    // Additional methods to handle relationship between builds and statuses
    // availabel members ...
    // -----------------------------------------
    std::map< std::string, HelpNDocAPI_ArgumentMap > HndBuildsStatusEx_FunctionNames = {
        {std::string("IsTopicIncludedInBuild" ), result_map }
    };
    
    // -----------------------------------------
    // HndBuildsTags:
    // Handle relationship between builds and tags.
    // availabel members ...
    // -----------------------------------------
    std::map< std::string, HelpNDocAPI_ArgumentMap > HndBuildsTags_FunctionNames = {
        {std::string("AreBuildAndTagAssociated"   ), result_map },
        {std::string("AssociateBuildWithTag"      ), result_map },
        {std::string("DissociateAllForTag"        ), result_map },
        {std::string("DissociateAllForBuild"      ), result_map },
        {std::string("DissociateBuildFromTag"     ), result_map },
        {std::string("GetTagsAssociatedWithBuild" ), result_map },
        {std::string("GetBuildsAssociatedWithTag" ), result_map }
    };
    
    // -----------------------------------------
    // HndBuildsTagsEx:
    // Additional methods to handle relationship between builds and tags.
    // availabel members ...
    // -----------------------------------------
    std::map< std::string, HelpNDocAPI_ArgumentMap > HndBuildsTagsEx_FunctionNames = {
        {std::string("ConditionAdd"           ), result_map },
        {std::string("ConditionInvert"        ), result_map },
        {std::string("ConditionRemove"        ), result_map },
        {std::string("ConditionReset"         ), result_map },
        {std::string("IsTopicIncludedInBuild" ), result_map }
    };
    
    
    // -----------------------------------------
    // HndEditor:
    // Create and manage a topic editor.
    // availabel members ...
    // -----------------------------------------
    std::map< std::string, HelpNDocAPI_ArgumentMap > HndEditor_FunctionNames = {
        {std::string("ApplyStyleToSelection"              ), result_map },
        {std::string("Clear"                              ), result_map },
        {std::string("ConvertParagraphBreaksToLineBreaks" ), result_map },
        {std::string("ConvertSelectionToSnippet"          ), result_map },
        {std::string("CreateTemporaryEditor"              ), result_map },
        {std::string("CreateTemporaryReportHelper"        ), result_map },
        {std::string("CreateTemporaryViewer"              ), result_map },
        {std::string("DestroyTemporaryEditor"             ), result_map },
        {std::string("DestroyTemporaryReportHelper"       ), result_map },
        {std::string("DestroyTemporaryViewer"             ), result_map },
        {std::string("GetAnchorList"                      ), result_map },
        {std::string("GetContentAsHtml"                   ), result_map },
        {std::string("GetContentAsStream"                 ), result_map },
        {std::string("GetContentAsText"                   ), result_map },
        {std::string("GetCurrentAnchorName"               ), result_map },
        {std::string("GetCurrentItem"                     ), result_map },
        {std::string("GetCurrentPictureAltText"           ), result_map },
        {std::string("GetCurrentPictureBackColor"         ), result_map },
        {std::string("GetCurrentPictureHeight"            ), result_map },
        {std::string("GetCurrentPictureMarginLeftRight"   ), result_map },
        {std::string("GetCurrentPictureMarginTopBottom"   ), result_map },
        {std::string("GetCurrentPicturePadding"           ), result_map },
        {std::string("GetCurrentPictureVAlign"            ), result_map },
        {std::string("GetCurrentPictureWidth"             ), result_map },
        {std::string("GetUsedLibraryItems"                ), result_map },
        {std::string("InsertAnchorBeforeCurrentItem"      ), result_map },
        {std::string("InsertCondition"                    ), result_map },
        {std::string("InsertContentFromHTML"              ), result_map },
        {std::string("InsertFile"                         ), result_map },
        {std::string("InsertFileFromLibraryItem"          ), result_map },
        {std::string("InsertHyperLinkToTopicId"           ), result_map },
        {std::string("InsertHyperLinkToUrl"               ), result_map },
        {std::string("InsertLibraryItem"                  ), result_map },
        {std::string("InsertLibraryItemContent"           ), result_map },
        {std::string("InsertPageBreakBeforeCurrentItem"   ), result_map },
        {std::string("InsertStream"                       ), result_map },
        {std::string("InsertTopicContent"                 ), result_map },
        {std::string("IsEmpty"                            ), result_map },
        {std::string("MoveCaret"                          ), result_map },
        {std::string("MoveCaretTo"                        ), result_map },
        {std::string("MoveCarretToEnd"                    ), result_map },
        {std::string("ProcessConditionalsForCurrentBuild" ), result_map },
        {std::string("RemoveCurrentAnchor"                ), result_map },
        {std::string("ReplaceLibraryItems"                ), result_map },
        {std::string("SetAsTopicContent"                  ), result_map },
        {std::string("SetContent"                         ), result_map },
        {std::string("SetCurrentCellsAlignment"           ), result_map },
        {std::string("SetCurrentPictureAltText"           ), result_map },
        {std::string("SetCurrentPictureBackColor"         ), result_map },
        {std::string("SetCurrentPictureHeight"            ), result_map },
        {std::string("SetCurrentPictureMarginLeftRight"   ), result_map },
        {std::string("SetCurrentPictureMarginTopBottom"   ), result_map },
        {std::string("SetCurrentPicturePadding"           ), result_map },
        {std::string("SetCurrentPictureVAlign"            ), result_map },
        {std::string("SetCurrentPictureWidth"             ), result_map },
        {std::string("SyntaxHighlightSelection"           ), result_map },
        {std::string("TogglePageBreak"                    ), result_map },
        {std::string("UpdateLibraryItem"                  ), result_map }
    };
    #endif
    
    // -----------------------------------------
    //
    //
    // availabel members ...
    // -----------------------------------------
    #if 0
    {std::string(""    ), {
    {std::string(""    ), {
    {std::string(""    ), {
    
    {std::string(""    ), {
    #endif

    // -----------------------------------------
    // HndBuildInfo:
    // Information about a specific build.
    // availabel members ...
    // -----------------------------------------
    std::map< std::string, HelpNDocAPI_ArgumentMap > HndBuildInfo_FunctionNames = {
        // Unique identifier of the build.
        {std::string("Id"), {
            { 0, _String }    // 0 = the result parameter: String
            }
        },
        // Kind of the build: code, chm, epub, html, kindle, pdf, qthelp, word
        {std::string("Kind"), {
            { 0, _String }    // 0 = the result parameter: String
            }
        },
        // Name of the build.
        {std::string("Name"), {
            { 0, _String }    // 0 = the result parameter: String
            }
        },
        // Is the build enabled ?
        {std::string("Enabled"), {
            { 0, _Bool }      // 0 = the result parameter: Boolean
            }
        },
        // Order of the build in the list. Greater will be built later.
        {std::string("Order"), {
            { 0, _Integer }   // 0 = the result parameter: Integer
            }
        },
        // Output path of the build.
        {std::string("Output"), {
            { 0, _String }    // 0 = the result parameter: String
            }
        },
        //Template name used for this build.
        {std::string("Template"), {
            { 0, _String }    // 0 = the result parameter: String
            }
        }
    };
public:
    // constructor
    HelpNDocAPI() {
        //HelpNDocAPI_ArgumentMap Arguments;
        //Arguments[ 1 ] = 1;
        
    //    for (const std::string& name : HndUtils_FunctionNames)
    //        HndUtils.push_back(name.first);
    }
};  // class HelpNDocAPI

// placeholders, to save disk space
std::string  HelpNDocAPI::_String  = std::string( "string"  );
std::string  HelpNDocAPI::_Bool    = std::string( "bool"    );
std::string  HelpNDocAPI::_Integer = std::string( "Integer" );
std::string  HelpNDocAPI::_TColor  = std::string( "TColor"  );

static class HelpNDocAPI HelpNDocAPI_Instance;

}   // namespace: HelpNDoc_Version7_9_1

// ---------------------------------------
// max include files for $include macro:
// ---------------------------------------
# define MAX_INCLUDE_DEPTH 10
YY_BUFFER_STATE include_stack[MAX_INCLUDE_DEPTH];

static int include_stack_ptr = 0;

static bool progressFile = false;    // stdin, or file ? (for the progress bar)
static int  progressMax  = 1;        // maximum of progress value (file lines)
static int  progressPos  = 1;        // current position cursor for progress bar
#line 1064 "parser.lex.cc"

#line 1066 "parser.lex.cc"

#define INITIAL 0
#define COMMENTS 1
#define TOK_INCLUDE 2
#define TOK_MAINPAGE 3
#define TOK_SUB_AUTOR 4
#define TOK_SUB_TITLE 5
#define TOK_SUB_VERSION 6
#define TOK_SUB_COPYRIGHT 7
#define TOK_SUB_SUMMARY 8

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 453 "parser.l"


#line 1294 "parser.lex.cc"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 193 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 378 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 455 "parser.l"
{ count(); BEGIN(INITIAL); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 457 "parser.l"
{ count(); BEGIN(COMMENTS); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 458 "parser.l"
{ count(); BEGIN(INITIAL);  }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 459 "parser.l"
{ count(); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 460 "parser.l"
{ count(); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 462 "parser.l"
{ count();     Number(); return TOK_NUMBER; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 463 "parser.l"
{ count(); HexaNumber(); return TOK_NUMBER; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 465 "parser.l"
{ count(); BEGIN(TOK_INCLUDE); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 466 "parser.l"
{ count(); BEGIN(TOK_INCLUDE); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 468 "parser.l"
{ count(); printf("-> mainpage"); BEGIN(TOK_MAINPAGE); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 469 "parser.l"
{ yyerror("@end does not enclose a block statement."); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 471 "parser.l"
{
	count();
	printf("inc: %s\n", yytext);
	
    // ---------------------------------
    // default max include are 10 files:
    // ---------------------------------
    if (include_stack_ptr >= MAX_INCLUDE_DEPTH) {
      fprintf(stderr, "Includes nested too deeply");
      exit(1);
    }

    include_stack[include_stack_ptr++] = YY_CURRENT_BUFFER;

    // ---------------------------------
    // remove first, and last qoute ...
    // ---------------------------------
    std::string f(yytext);
    f.erase(0,1);
    f.erase(f.size() - 1);
    
    char *buffer = (char*) malloc(128);
          buffer = &(f[0]);

    if (!(yyin = fopen(buffer, "r"))) {
        sprintf(buffer,"file not: %s found.", yytext);
        yyerror(buffer);
    }
    
    // ---------------------------------
    // parse the $include "file" :
    // ---------------------------------
    yy_switch_to_buffer(
    yy_create_buffer(yyin, YY_BUF_SIZE));

	BEGIN(INITIAL);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 509 "parser.l"
{ count(); tmpvec.clear(); printf("--> autor  : "); BEGIN(TOK_SUB_AUTOR);     }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 510 "parser.l"
{ count(); tmpvec.clear(); printf("--> title  : "); BEGIN(TOK_SUB_TITLE);     }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 511 "parser.l"
{ count(); tmpvec.clear(); printf("--> version: "); BEGIN(TOK_SUB_VERSION);   }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 512 "parser.l"
{ count(); tmpvec.clear(); printf("--> copyr  : "); BEGIN(TOK_SUB_COPYRIGHT); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 513 "parser.l"
{ count(); tmpvec.clear(); printf("--> summary: "); BEGIN(TOK_SUB_SUMMARY);   }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 515 "parser.l"
{ count(); printf("-> end\n"); BEGIN(INITIAL); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 516 "parser.l"
{ count(); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 518 "parser.l"
{ count(); }
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 519 "parser.l"
{ count(); handle_str(); BEGIN(TOK_MAINPAGE); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 520 "parser.l"
{ count(); tmpvec.push_back(*yytext); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 522 "parser.l"
{ count(); }
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 523 "parser.l"
{ count(); handle_str(); BEGIN(TOK_MAINPAGE); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 524 "parser.l"
{ count(); tmpvec.push_back(*yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 526 "parser.l"
{ count(); }
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 527 "parser.l"
{ count(); handle_str(); BEGIN(TOK_MAINPAGE); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 528 "parser.l"
{ count(); tmpvec.push_back(*yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 530 "parser.l"
{ count(); }
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 531 "parser.l"
{ count(); handle_str(); BEGIN(TOK_MAINPAGE); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 532 "parser.l"
{ count(); tmpvec.push_back(*yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 534 "parser.l"
{ count(); }
	YY_BREAK
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 535 "parser.l"
{ count(); handle_str(); BEGIN(TOK_MAINPAGE); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 536 "parser.l"
{ count(); tmpvec.push_back(*yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 539 "parser.l"
{
    count();
    printf("op: %s\n", yytext);
    return *yytext;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 545 "parser.l"
{ count(); }
	YY_BREAK
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 546 "parser.l"
{ count(); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENTS):
case YY_STATE_EOF(TOK_INCLUDE):
case YY_STATE_EOF(TOK_MAINPAGE):
case YY_STATE_EOF(TOK_SUB_AUTOR):
case YY_STATE_EOF(TOK_SUB_TITLE):
case YY_STATE_EOF(TOK_SUB_VERSION):
case YY_STATE_EOF(TOK_SUB_COPYRIGHT):
case YY_STATE_EOF(TOK_SUB_SUMMARY):
#line 548 "parser.l"
{
    // ----------------------------------------------
    // check, if end of file, is it in main document,
    // terminate parser session; else: return back to
    // previously file ...
    // ----------------------------------------------
    if (--include_stack_ptr < 0) {
        yyterminate();
    }   else {
        yy_delete_buffer( YY_CURRENT_BUFFER);
        yy_switch_to_buffer(
        include_stack[ include_stack_ptr ]);
    }
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 563 "parser.l"
;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 565 "parser.l"
ECHO;
	YY_BREAK
#line 1629 "parser.lex.cc"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 193 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 193 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 192);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 565 "parser.l"

//-- FUNCTION DEFINITIONS ---------------------------------

// --------------------------------
// console error output:
// --------------------------------
int yyerror(const char *p) {
    std::cout << "Error: "
              << std::dec << line_row << ":"
              << std::dec << line_col << ": "
              << p        <<
    std::endl ;
    exit(1);
}

// --------------------------------
// convert string to int64
// --------------------------------
void Number () {
    yylval.val_int64 = atol(yytext);
}

// --------------------------------
// convert hex string to int64
// --------------------------------
void HexaNumber () {
    yylval.val_int64 = (unsigned int) strtol(yytext, (char **)NULL, 16);
}

// --------------------------------
// count character position:
// --------------------------------
void count(void)
{
    int i;
    for (i = 0; yytext[i] != '\0'; i++) {
	    if (yytext[i] == '\n')  { line_col  = 0; ++line_row; } else
	    if (yytext[i] == '\t')  { line_col += 1;             } else line_col++;
    }
}

// --------------------------------
// trim trailing space from tmpvec
// --------------------------------
void handle_str()
{
    std::string id;
	
    for (char value: tmpvec)
    id +=  value;
	
    ltrim(id);
    std::cout << id << std::endl;
}

// --------------------------------
// application entry point:
// --------------------------------
int main(int argc, char **argv)
{
    int  result = 0;

    // --------------------------------------------------
    // copyright banner - please dont remove it.
    // --------------------------------------------------
    std::cout << "helpconv (c) 2022 Jens Kallup <kallup.jens@web.de>" <<
    std::endl << "all rights reserved." <<
    std::endl <<
    std::endl ;

    // --------------------------------------------------
    // argument must given, for file name; else stdin :
    // --------------------------------------------------
    if (argc < 2) {
        std::cout << "no file given." <<
        std::endl ;
        return 1;
    }

    std::vector< std::string > args(argv, argv + argc);
    for (const std::string& item : args)
        std::cout << item << std::endl;
    
    return 0;
    
    // --------------------------------------------------
    // I use the C version of "flex + bison", so we have
    // to use old C functions to parse the source file :
    // --------------------------------------------------
    if (!(yyin = fopen(argv[1],"r"))) {
        std::cerr << "error: can't find input file: "
                  << argv[1]
                  <<
        std::endl << "use default stdin." <<
        std::endl ;

        yyset_in(stdin);
    }   else {
        int ch = 0;
        
        // get line numbers
        progressMax = 1;
        while ((ch  = fgetc(yyin)) != EOF) {
            if (ch == '\n')
            progressMax++;
        }
        
        std::cout << "Lines: " << std::dec << progressMax <<
        std::endl ;
        
        yyset_in(yyin);
        progressFile = true;
    }

    result = yylex();
	
    fclose(yyin);
    return result;
}

